acme_hello_homepage:
    path:     /hello/{name}
    defaults: { _controller: AcmeHelloBundle:Default:index }
acme_email_test:
    path:     /testemail
    defaults: { _controller: AcmeHelloBundle:Default:testEmail }
