Shoppinglist\ApiBundle\Entity\User:
    type: entity
    table: user
    uniqueConstraints:
        email_UNIQUE:
            columns:
                - email
    id:
        idUser:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            column: id_user
            generator:
                strategy: IDENTITY
    fields:
        email:
            type: string
            nullable: false
            length: 100
            fixed: false
            comment: ''
        firstName:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: first_name
        lastName:
            type: string
            nullable: false
            length: 45
            fixed: false
            comment: ''
            column: last_name
        gender:
            type: boolean
            nullable: false
            comment: ''
            default: '1'
        pass:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
        mobileNo:
            type: string
            nullable: false
            length: 15
            fixed: false
            comment: ''
            column: mobile_no
        apiKey:
            type: string
            nullable: true
            length: 64
            fixed: false
            comment: ''
            column: api_key
        emailVerified:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: email_verified
        status:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        isAdmin:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: is_admin
        createdAt:
            type: datetime
            nullable: true
            comment: ''
            default: '0000-00-00 00:00:00'
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            comment: ''
            default: '0000-00-00 00:00:00'
            column: updated_at
    lifecycleCallbacks: {  }
