shoppinglist_admin:
    resource: "@ShoppinglistAdminBundle/Resources/config/routing.yml"
    prefix:   /admin

shoppinglist_api:
    resource: "@ShoppinglistApiBundle/Resources/config/routing.yml"
    
hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"