<?php

namespace Shoppinglist\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * 
     * @return type
     */
    public function getAllCategories()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT '
                    . 'c.idCategory, c.categoryName FROM ShoppinglistApiBundle:Category c '
                    . 'WHERE c.status = 1'
            )->getResult();
    }
}
