<?php

namespace Shoppinglist\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function getAllProducts($categoryId = null)
    {
        $query = $this->createQueryBuilder('p')->orderBy('p.productName', 'ASC');
        if ($categoryId) {
            $query->where('p.fkCategory = :fkCategory')->setParameter('fkCategory', $categoryId);
        }

        return $query->getQuery()->getResult();
    }
}
