<?php

namespace Shoppinglist\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination;

/**
 * ShoppinglistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShoppinglistRepository extends EntityRepository
{
    /**
     * This function will get all shoppinglists of given user
     * 
     */
    public function getAllListing($userId, $limit = 30, $offset = 1)
    {
        return $this->getEntityManager()
                ->createQuery(
                    'select s.shoppinglistName, s.idShoppinglist, s.createdAt '
                    . ' from ShoppinglistApiBundle:Shoppinglist s '
                    . 'where s.fkUser = :userId order by s.createdAt DESC'   
                        
                )->setMaxResults($limit)
                ->setFirstResult($offset)
                ->setParameter(':userId', $userId)
                ->getResult();
    }
    
    public function deleteShoppinglistByIds($ids, $userId)
    {
        return $this->getEntityManager()
                ->createQuery(
                    'DELETE '
                    . ' FROM ShoppinglistApiBundle:Shoppinglist s '
                    . 'WHERE s.idShoppinglist IN (:ids) AND s.fkUser = :userId'   
                        
                )->setParameter(':ids', $ids)
                ->setParameter(':userId', $userId)
                ->execute();
    }
}
