<?php

namespace Shoppinglist\ApiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * 
     * @param string $email
     * @return type
     */
    public function getUserDetailByEmail($email)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT '
                    . 'u.email as email, u.pass as pass, u.idUser as id, u.emailVerified as email_verified,u.firstName as first_name, u.lastName as last_name, u.apiKey as api_key '
                    . 'FROM ShoppinglistApiBundle:User u '
                    . 'WHERE u.email = :email AND u.status = 1'
            )->setParameter(':email', $email)
            ->getOneOrNullResult();
    }
    
    /**
     * Not in use
     * 
     * @param type $apiKey
     * @return type
     */
    public function getUserByApiKey($apiKey)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT '
                    . 'u.idUser as id_user '
                    . 'FROM ShoppinglistApiBundle:User u '
                    . 'WHERE u.apiKey = :apikey AND u.status = 1'
            )->setParameter(':apikey', $apiKey)
            ->getOneOrNullResult();
    }
}
